TARGETS = ctlr

CC = gcc
OUTPUT_OPTION=-MMD -MP -o $@
CFLAGS = -g -O2 -Wall -Wno-unused-result -Iutil -I/usr/local/include/libpololu-tic-1

SRC_CTLR = ctlr.c \
           util/util_misc.c

OBJ_CTLR=$(SRC_CTLR:.c=.o)

DEP=$(SRC_CTLR:.c=.d) 

#
# build rules
#

all: $(TARGETS)

ctlr: $(OBJ_CTLR) 
	$(CC) -pthread -lrt -lm -lreadline -lpololu-tic-1 -o $@ $(OBJ_CTLR)

-include $(DEP)

#
# clean rule
#

clean:
	rm -f $(TARGETS) $(OBJ_CTLR) $(DEP)

